### PR TITLE
build(image): switch to sle bci based image

### PR DESCRIPTION
**Pull request by starbops**
Signed-off-by: Zespre Chang <zespre.chang@suse.com>

harvester/harvester#3149

### CODE REVIEW

**Comment by bk201** [comment]
@starbops https://github.com/harvester/harvester-csi-driver/blob/24519c253d02affa05e6f1e8337a6e16cea28cf7/Dockerfile.dapper#L1 is already on 1.18, please help rebase. Thanks!

**Comment by starbops** [comment]
> @starbops
> 
> https://github.com/harvester/harvester-csi-driver/blob/24519c253d02affa05e6f1e8337a6e16cea28cf7/Dockerfile.dapper#L1
> 
> is already on 1.18, please help rebase. Thanks!

@bk201 The PR is rebased, please review it again. Thanks!

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, test build successfully.

**Review by bk201 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
