### PR TITLE
move driver base imge to bci

### PR DESCRIPTION
**Pull request by joshmeranda**
Move csi driver base image to `bci-base:15.4` from alpine.

Issue [#1995](https://github.com/harvester/harvester/issues/1995)

### CODE REVIEW

**Comment by guangbochen** [comment]
@joshmeranda is this PR ready for review, feel free to assign @bk201 and me next time if u don't who to request, thanks.

**Review by w13915984028 — APPROVED** [review]
LGTM, thanks.

**Review by Vicente-Cheng — APPROVED** [review]
Test with the new image and `zypper` command.
LGTM!

**Comment by joshmeranda** [comment]
@guangbochen Yes this is ready for review. I will assign you two next time, thanks!

**Pull request merged**
