### PR TITLE
update golang build version 1.8.3

### PR DESCRIPTION
**Pull request by joshmeranda**
Bump the golang build version from `1.16.2` to `1.18.3` per [this comment](https://github.com/harvester/harvester/issues/1995#issuecomment-1212683872).

@guangbochen

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
We need to bump the [go mod version](https://github.com/harvester/harvester-csi-driver/blob/master/go.mod#L3) as well, thanks.

**Comment by joshmeranda** [comment]
@guangbochen bumped go mod version `go 1.18`

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, also the Image is already SLE BCI 15.4.
we do not need to patch it again

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
