### PR TITLE
Bump golang to v1.21

### PR DESCRIPTION
**Pull request by votdev**
**Problem:**
Go v1.20 is EOL on 06 Feb 2024.

**Solution:**
Bump golang to v1.21.

Need to upgrade `github.com/longhorn/longhorn-manager` to `v1.5.4` because `github.com/honestbee/jobq` does not exist anymore. See https://github.com/harvester/harvester/issues/4651 for more information.

**Related Issue:**
https://github.com/harvester/harvester/issues/5310

### CODE REVIEW

**Review by connorkuehl — APPROVED** [review]
LGTM. I'm not worried about the longhorn-manager bump as it seems like we only pull in that module for a constant and a utility function to round up a number. So it's not like we have to worry about potential differences in API surface depending on which version of Harvester we're running under (iirc, versions < Harvester 1.3.0 == Longhorn 1.5, whereas ?= Harvester 1.3 onwards has 1.6)

Tempted to remove the dependency and "vendor" the const and the utility func, seeing as they have not changed since 2020 and 2017, respectively:

```console
~/src/longhorn-manager> git log -SMinimalVolumeSize ./util/
commit ee35aa86e46e0c0fc17ba3a6f6b42f0319434ab6
Author: Bo Tao <bo.tao@rancher.com>
Date:   Thu Oct 22 17:00:25 2020 -0700
~/src/longhorn-manager> git log -SRoundUpSize ./util/
commit 0cff3c0e9daac5e5e1a336b186145d224beb3559
Author: Sheng Yang <sheng@yasker.org>
Date:   Thu May 4 18:37:49 2017 -0700
```

**Comment by bk201** [comment]
> Tempted to remove the dependency and "vendor" the const and the utility func, seeing as they have not changed since 2020 and 2017, respectively:

@connorkuehl Should we do this in this PR or another one?

**Comment by connorkuehl** [comment]
> > Tempted to remove the dependency and "vendor" the const and the utility func, seeing as they have not changed since 2020 and 2017, respectively:
> 
> @connorkuehl Should we do this in this PR or another one?

Up to @votdev. I'm happy to file a followup once this is merged.

**Review by Vicente-Cheng — APPROVED** [review]
lgtm!

**Pull request merged**
